### ISSUE TITLE
Feature Request: Be able to define ApiSufix in Task

### ISSUE THREAD

**Issue by elvirdolic** [stephaneey/azure-apim-extension#1]
It would be great to have the possibility to define the api suffix property in the task

![image](https://user-images.githubusercontent.com/17769458/37403107-0c6cecfa-278e-11e8-90d5-6b7fa25c6c9f.png)

**Comment by stephaneey** [comment]
You're right, I had it in the radar then I forget. I'll quickly add it, stay tunned :)

**Comment by elvirdolic** [comment]
Any progress on this?

**Comment by stephaneey** [comment]
Sorry, should work on this over the weekend

**Comment by stephaneey** [comment]
Done & released
