### ISSUE TITLE
Web service URL blank after update

### ISSUE THREAD

**Issue by francesco-scullino** [stephaneey/azure-apim-extension#106]
Hello,
the **Web service URL** become blank using the task in a YAML pipeline. 

<img width="450" alt="image" src="https://user-images.githubusercontent.com/1720798/100857734-5a014d80-348d-11eb-8476-d266d3d79bec.png">

This issue don't exist using a classic pipeline. I compared the generated YAML from classic pipeline and it is the same as the one I created in YAML pipeline.

What is the YAML parameter for **Web service URL**?

**Comment by francesco-scullino** [comment]
The error was not in the task but for the missing server url in the swagger definition

**Comment by MattHartz** [comment]
Can we reopen this? When deploying to different environments, i would like to be able change this in a given pipeline

**Comment by alanta** [comment]
I'm with @MattHartz on this. We're generating the swagger json in a build and then deploying that to different environments. I need a way to specify the URL in the task to be able to do that.
