### ISSUE TITLE
Feature request: Load swagger definition from (artifact) file

### ISSUE THREAD

**Issue by anton-g** [stephaneey/azure-apim-extension#11]
This looks amazing and is exactly what I've been looking for for a while now.
The only thing I'm missing is being able to load the swagger definition from a file. We generate our definitions when we build the solution in VSTS, and this would be the last part missing from a fully automated work flow.

I might take a stab at this myself, but my knowledge in both VSTS task creation and powershell are a bit lacking.

Great job with the extension so far! :tada:

**Comment by stephaneey** [comment]
Hi @anton-g ,

Thanks for the feedback. I'm going to look into that as well.

Best Regards

**Comment by lurumad** [comment]
Hi @anton-g

Maybe you can publish your swagger definition from VSTS build to some place like an storage account and try to reference from VSTS task.

Regards!

**Comment by stephaneey** [comment]
Well, I think that just getting it as a build artifact should do the trick. For the storage account, with the current task, you might already achieve it as I'm asking for a URL, it could be the URL of your blob with a SAS that is long enough.

**Comment by stephaneey** [comment]
Hi @lurumad ,

sorry, I just realize that you were responding to @anton-g  :). Indeed, he can do what you suggest with the current solution. I'll still have a look at getting the swagger file as a build artifact on top of the 2 other possibilities.

Best Regards

**Comment by stephaneey** [comment]
Hi @anton-g 

Just released! You may now provide the Swagger definition as a build artifact. I also updated the documentation on the marketplace to make your API Host dynamic across your release pipeline. This is in theory beyond the API Management extension itself but I thought it'd be interesting to provide a way to cope with multiple environments.

Best Regards
