### ISSUE TITLE
API Management - Create/Update API  - Make fields editable with variables

### ISSUE THREAD

**Issue by DibranMulder** [stephaneey/azure-apim-extension#16]
![image](https://user-images.githubusercontent.com/5592416/47024261-9e241d80-d161-11e8-873f-04922e9a140a.png)

When I want to use this task in a Task group then I'll have to work with variables. Once I've used one variable in the Subscription field I'm not able to use others in for instance the Resource Group field. 

The following fields should be editable with variables:
* Subscription
* Resource group
* API Portal
* Product

The others work just fine. Thanks in advance. If you need anything please ask me.

**Comment by stephaneey** [comment]
Hi @DibranMulder ,

Ok I get it, it is simply because I didn't make the picklists editable. It's not a big change but I'll probably do it in a few days. I'm right now quite busy at a conference so I'm running out of time. Stay tuned, I'll change that soon.

Best Regards

**Comment by stephaneey** [comment]
Hi @DibranMulder,

I've updated the extension.

Best Regards

**Comment by DibranMulder** [comment]
Ok thanks! When will the marketplace be updated?

**Comment by DibranMulder** [comment]
Ah I see the extension is updated, thanks for the super fast response!

**Comment by stephaneey** [comment]
Hi @DibranMulder ,

I'll fix this over the week-end and basically, I'll review all the tasks just to be sure.

Thanks
