### ISSUE TITLE
Can't create groups

### ISSUE THREAD

**Issue by DibranMulder** [stephaneey/azure-apim-extension#17]
It would be nice if you could create a group via Azure DevOps. Now I have to add one of the default groups to a Product.

**Comment by stephaneey** [comment]
@lurumad will you be working on this?

Thanks

**Comment by lurumad** [comment]
Ok @stephaneey if you want integrate my changes it's perfect because I'm on holidays until monday.

Regards!

**Comment by stephaneey** [comment]
Hello,

It has been added and published to the marketplace.

Best Regards

**Comment by DibranMulder** [comment]
Sweet!
