### ISSUE TITLE
API Management - Create or Update API on Azure Functions - Make fields editable with variables

### ISSUE THREAD

**Issue by DibranMulder** [stephaneey/azure-apim-extension#19]
![image](https://user-images.githubusercontent.com/5592416/47488206-2da58c80-d844-11e8-9610-1113238393e1.png)
When I want to use this task in a Task group then I'll have to work with variables. One field is not editable, namely:
- Functions Resource Group

 Simular issue as #16

**Comment by stephaneey** [comment]
Hello,

Done and published!

Best Regards

**Comment by DibranMulder** [comment]
You are fast 🥇 👍
