### ISSUE TITLE
Create or Update Versioned API From Azure Function for AF v2

### ISSUE THREAD

**Issue by R0binT** [stephaneey/azure-apim-extension#24]
Hi,
I have azure function which are on the v2.
The thing is that the OpenApi feature is not supported yet.
So the problem is when the task try to get the swagger from it.
I get that error : 
`[error]You cannot call a method on a null-valued expression.`
Would it be possible the give an external swagger file ?

Thanks

**Comment by R0binT** [comment]
<img width="1151" alt="screenshot 2018-11-14 at 14 50 32" src="https://user-images.githubusercontent.com/6819007/48486745-b2207500-e81c-11e8-9db8-1e2398e3ea06.png">

**Comment by mavvoorn** [comment]
We have the same thing

**Comment by stephaneey** [comment]
Hello,

I don't think I will implement this as modifying the extension will most probably cause many other issues later on as there is a tight coupling between the function name and its OpenAPI counterpart. If I let people generate their own swagger and if they fail to respect (or simply do not want) this, the task won't be able to generate the operation-level policy that injects the function key...and many people will be confused.

On my side, I prefer to wait until V2 supports OpenAPI. However, feel free to fork the repo and implement it for your own needs.

Best Regards

**Comment by PatrikNorrgard** [comment]
Any news on this Function V2 support? You can import an Function V2 app from the Api Management GUI, by selecting "Function app", so there must be a way to do it without OpenApi (swagger). I did not see a command for this in the Azure Rest API, but maybe in Power shell?
