### ISSUE TITLE
No Policy can be set when Policy selection is set to 'None'

### ISSUE THREAD

**Issue by bmargula** [stephaneey/azure-apim-extension#3]
As I can see in task.json of apim folder, the None option for Policy has a wrong visibleRule.

```json
{
      "name": "None",
      "type": "string",
      "label": "None",
      "defaultValue": "<policies>\n\t<inbound>\n\t\t<base />\n\t</inbound>\n\t<backend>\n\t\t<base />\n\t</backend>\n\t<outbound>\n\t\t<base />\n\t</outbound>\n\t<on-error>\n\t\t<base />\n\t</on-error>\n</policies>",
      "helpMarkDown": "",
      "visibleRule": "TemplateSelector = NAN"
    }
```
therefore preventing to show the field to apply your own policy.

Question: My existing policy in API management is always overwritten even when selecting 'None'. How can this be prevented?

**Comment by stephaneey** [comment]
Hi,

Thanks for reporting this bug. In the meantime, you can select anything else but the "none" policy and override the default template with your content. It's a nasty workaround but should unblock you.

Best Regards

**Comment by stephaneey** [comment]
Just realized one thing: it's a normal behavior that when you select "None" you cannot define any policy, that's the desired behavior. However, I added a new choice "custom" that lets you specify anything without overriding a predefined template.
