### ISSUE TITLE
In which release will Microsoft API version selector be available

### ISSUE THREAD

**Issue by Sid3way** [stephaneey/azure-apim-extension#35]
Hello,

I was wondering in which release the commit [https://github.com/stephaneey/azure-apim-extension/commit/2dd41ae82fe05dab87cad4b929546b836d11690c](url) will be made available.

Thank you very much for your amazing work !

Sid3way

**Comment by stephaneey** [comment]
It's already available but right now only for the task "API Management - Create or Update Versioned API"

**Comment by Sid3way** [comment]
Thank you for your fast response.
Is there any plan to make it available to the `Create or Update API` task ?
I tried using the one for the versioned API but I ended up with a rather generic error
```
You cannot call a method on a null-valued expression. 
```

I suspect that something went wront. I duplicated the configuration from my other task but there may be some prerequisites for versionned API that I'm not aware of.

**Comment by stephaneey** [comment]
Well, the thing is: the versioned API is intended to be used from scratch, meaning that if you try to deploy a versioned API on an existing API that you deployed with the non-versioned API task, it is likely to fail. I'll try to update the other tasks to use the same version selector this week-end. Stay tunned!

**Comment by Sid3way** [comment]
Ok, it makes perfect sense in my case indeed.
I'll wait for your much appreciated update.

Thank you again for your work :)

**Comment by KZeronimo** [comment]
Just to be clear this should enable the import of an Open API v3 document - correct?

**Comment by stephaneey** [comment]
Hello,

I've added the version selector to two other tasks. I will publish the extension any time soon. 

Best Regards

**Comment by alprema** [comment]
Hi,

I am also interested in this issue, so I looked at the commit log and couldn't find a commit matching the modification you mentioned when you closed this issue (or any commit after end of January).

Is this still a work in progress?

Thanks
