### ISSUE TITLE
Content Format use openlink-api

### ISSUE THREAD

**Issue by KZeronimo** [stephaneey/azure-apim-extension#36]
Now with APIM supporting OpenApi v3 would it be appropriate to change `contentFormat: swagger-json` to `contentFormat: openlink-api`

I did a quick smoke test and the latter support importing both v2 and v3 artifacts

Thoughts?

**Comment by stephaneey** [comment]
Hello,

Indeed, that makes sense. I'll add it to the list of things to do for the next release.

Thanks
Best Regards

**Comment by stephaneey** [comment]
Hi,

Tried it out.  FYI, it is not openlink-api but openapi-link and it only works with v3. While you might think it works with v2, you'll notice that your web service URL will be screwed up. The doc states that it only works with v3 anyway. I'm now waiting for MS feedback as I can't get it work with a native YAML definition. To be more explicit, the openapi-link works with both but trying to send the YAML content using "openapi" doesn't and I'd like to have all the possibilities.

Best Regards

**Comment by stephaneey** [comment]
Hello,

It is working now. I'll publish the new version next week-end as I'll be out for a few days so I don't want to take the risk to publish a new release (there are other changes too) while not being available.

Best Regards

**Comment by thomasvdb** [comment]
Will it also support openapi+json?

**Comment by stephaneey** [comment]
Yep it will. I'll finish that next Sunday

**Comment by stephaneey** [comment]
Hello,

The last release supports this scenario.

Best Regards
