### ISSUE TITLE
Save/Restore style and template of Developer portal

### ISSUE THREAD

**Issue by TLaborde** [stephaneey/azure-apim-extension#38]
Hi,

Do you think you could had feature to save and restore the style of the developer Portal? I found a way to do so in powershell and use a build task using Azure Powershell. It's using undocumented endpoints, but it works...

**Comment by stephaneey** [comment]
Hello,

Thanks for your suggestion but I prefer not to work with undocumented endpoints as they might simply be discarded or changed completely by MS with no backward compatibility. 

Best Regards
