### ISSUE TITLE
API URL suffix

### ISSUE THREAD

**Issue by lurumad** [stephaneey/azure-apim-extension#4]
Hi,

How can I specify "API URL suffix" in the Creation/Update of Gateway APIs task?

Regards!

**Comment by stephaneey** [comment]
Hi,

This is actually the API name parameter.

Best Regards

**Comment by lurumad** [comment]
Hi @stephaneey 

I think is not good idea to share this variable for the name and suffix. For example in Azure Api Management import cmdlet, you specify the path but Api Managment takes the name from swagger specification.

In this case I prefer to choose both of them, but is not possible, I prefer the way of import cmdlet works.

Regards!
