### ISSUE TITLE
Validation Error

### ISSUE THREAD

**Issue by vaseems** [stephaneey/azure-apim-extension#40]
2019-03-06T10:21:38.1870541Z @{code=ValidationError; target=representation; message=Parsing error(s): JSON is valid against more than one schema from 'oneOf'. No valid schemas. Path 'paths./user.post.parameters[0]', line 1, position 879.}
2019-03-06T10:21:38.4594175Z ##[error]The remote server returned an error: (400) Bad Request.

Getting this error for the below swagger json

`"/user": {
  "post": {
    "description": "description",
    "tags": [
      "moveforward"
    ],
    "produces": [
      "application/json"
    ],
    "parameters": [
      {
        "in": "body",
        "schema": {
          "type": "array",
          "$ref": "#/definitions/Request"
        },
        "description": "Process Description"
      }
    ],
    "responses": {
      "200": {
        "description": "users response",
        "schema": {
          "type": "object",
          "$ref": "#/definitions/Response"
        }
      }
    }
  }
}`

Definitions I have 

`"Request": {
"type": "array",
"items": {
"type": "string"
}
},
"Response": {
"type": "object"
}`

After repeated tries sometimes it works without any change.

Any help would be appreciated.

**Comment by thomasvdb** [comment]
I have the same issue when using the "Create/Update API" task.
Our swagger.json contains the following section:

```
    "securityDefinitions": {
        "oauth2": {
            "flow": "implicit",
            "authorizationUrl": "...",
            "tokenUrl": "...",
            "scopes": {
                 ...
            },
            "type": "oauth2"
        }
    },
    "security": [
        {
            "oauth2": [
                ""
            ]
        }
    ]
```

Receiving the following error: 
```
2019-03-29T07:59:21.6744381Z @{code=ValidationError; target=representation; message=Parsing error(s): JSON is valid against more than one schema from 'oneOf'. No valid schemas. Path 'securityDefinitions.oauth2', line 1, position 1371.}
```

Any idea what could cause this issue?

**Comment by stephaneey** [comment]
Hello,

The 400 error message is returned by the Azure Management API itself. The extension is not responsible for this. The extension simply forwards your JSON or YAML declaration to the Azure API, just make sure it is correct. Pay attention not to have weird chars in your document, certainly when working with the artifact and the code way of bringing your specs.
