### ISSUE TITLE
Support OpenApi 3 json

### ISSUE THREAD

**Issue by Farre82** [stephaneey/azure-apim-extension#41]
Are you planning to support openapi spec. When trying to use such spec i m getting missing swagger version error.

**Comment by stephaneey** [comment]
Hi,

I'm working on it.

Best Regards

**Comment by stephaneey** [comment]
Hi,
I'm trying to get it work with a native YAML file. Reached out to MS about it as it keeps failing.
Best Regards

**Comment by stephaneey** [comment]
Hello,

It is working now. I'll publish the new version next week-end as I'll be out for a few days so I don't want to take the risk to publish a new release (there are other changes too) while not being available.

Best Regards

**Comment by Farre82** [comment]
Thanks!
