### ISSUE TITLE
API Management - Create or Update Versioned API select different Api Version hides version scheme

### ISSUE THREAD

**Issue by MarcoK80** [stephaneey/azure-apim-extension#42]
If you rewrite the API version from v1 to 1 for example then the API versioning scheme configuration gets hidden.
Reproducable with task API Management - Create or Update Versioned API in version 2 and 3.

**Comment by stephaneey** [comment]
Hello,

Indeed, the declarative approach of Azure DevOps task is sometimes a limiting factor. "v1" is part of a display rule of another control and cannot be changed. You have to live with this limitation or customize the task for your own use only.

Best Regards
