### ISSUE TITLE
API Management - Create or Update Versioned API: Deploy of version 2 or 3 overwrites version 1

### ISSUE THREAD

**Issue by MarcoK80** [stephaneey/azure-apim-extension#45]
We have two or three sequential tasks with different swagger files and versions. When running the tasks we observed that sporadically the version 1 is overwritten with content of version 2 or 3 after some releases
So the task is not reliable.

We tested and found if we call the tasks in order 
API Version 2
API Version 1
then it overwrites the API Version 2 sporadically. So always the last task is sporadically overwriting the tasks before.

The only way to fix this is to delete all versions and rerun the tasks and cross fingers that it is not overwriting it.

**Comment by stephaneey** [comment]
Hello,

I can't reproduce this.

Best Regards
