### ISSUE TITLE
Ability to import swagger for existing API and create a new revision from it

### ISSUE THREAD

**Issue by R-Lamberson** [stephaneey/azure-apim-extension#46]
Looking for the ability to create a revision to an existing api during the import of the swagger either by setting a specific revision number or allowing it to auto generate

**Comment by rndthoughts** [comment]
I was looking at this too, but my understanding is that you can't create a revision from a swagger definition.

**Comment by stephaneey** [comment]
Hello @R-Lamberson  @rndthoughts ,

Indeed, you can't create new revisions while importing. The sequence is:

- Create a revision from another one
- Import

So, I'll work on making this transparently. I'll add a checkbox "Create new revision" which when checked will first create a revision and then import the OpenAPI definition. If unchecked, it will behave like today, meaning overwriting the current revision.

Stay tuned!

Best Regards

**Comment by stephaneey** [comment]
Currently in preview
