### ISSUE TITLE
uniqueItems is not a valid property (error returned by Api Azure Management)

### ISSUE THREAD

**Issue by JuanJose-Herrera** [stephaneey/azure-apim-extension#47]
HI @stephaneey,

Firs I want to thank you with the grate job for this pipeline for Azure Api Management. 

I don't think this is an issue from you code, but I am requesting your help about if you understand why microsoft return me an error updating the Api from the azure pipe line using powershell and not from the UI.

The error showed by the pipeline is:
`2019-04-27T17:59:17.4449422Z Creating or updating API https://management.azure.com/subscriptions/################/resourceGroups/dev-resourcegroup/providers/Microsoft.ApiManagement/service/dev-ocufile-api/apis/user-profile-rest-api?api-version=2018-01-01
2019-04-27T17:59:18.5303686Z @{code=ValidationError; target=representation; message=Parsing error(s): uniqueItems is not a valid property at #/paths//doctor/me/specialties/get/parameters []}
2019-04-27T17:59:18.8508790Z ##[error]The remote server returned an error: (400) Bad Request.
2019-04-27T17:59:18.9137634Z ##[section]Finishing: API Management - Create/Update API 
`

![image](https://user-images.githubusercontent.com/35985447/56869867-1c446500-69cc-11e9-8988-356eb12e75e1.png)

If you see the image my definition of the api contains an array of string with the unique keyword equals false, and that is that microsoft send me as not valid, I dont know why, beacuas actualy that is a valid value in the OpenAPI documentation.

The documentation that I review is:  https://swagger.io/docs/specification/data-models/data-types/#array
Note: I try to update the api with openAPI v2 and V3

**Comment by stephaneey** [comment]
Hi @JuanJose-Herrera ,

The doc you mentioned is indeed applicable to OpenAPI v3. Please use the task with v3.

Thanks
