### ISSUE TITLE
Create or Update Versioned API 3.3.0: Error when version number contains a dot

### ISSUE THREAD

**Issue by FelixBoers** [stephaneey/azure-apim-extension#49]
Creating or updating a versioned API results in an error when the version contains a dot.

API Name: my-api
API Version: 1.0

_@{code=ValidationError; target=aid; message=Invalid identifier my-api1.0 specified.  Entity Identifier can contain only letters, numbers, and hyphens. The first and last character must be a letter or a number }_

---

Task Version: 3.3.0
Microsoft API Version: 2018-01-01

**Comment by FelixBoers** [comment]
I'll create a pull request for this issue.

**Comment by stephaneey** [comment]
Hi Felix,

Thanks!

**Comment by FelixBoers** [comment]
I think, the error is in line 234 of the `apimversioned/v3/apimversioned.ps1` script file:

```powershell
$newversionurl="$($baseurl)/apis/$($newapi)$($v);rev=1?api-version=$($MicrosoftApiManagementAPIVersion)"
```

Doesn't this result in a wrong url? For example if `$newapi="my-api"` and `$v="1.0"` the url results in `.../apis/my-api1.0;rev=1?api-version=...`.

Why is there a concat of `$newapi` and `$v` in the first place? Shouldn't it be only `$newapi`?

**Comment by stephaneey** [comment]
yes it probably is the error. However, you should test with Fiddler (or postman) first to make sure you do not have side effects. The Azure APIs also have new capabilities since the time I started the extension..To be checked!

**Comment by FelixBoers** [comment]
Seems like, the format of the URL is correct: [see documentation](https://docs.microsoft.com/en-us/rest/api/apimanagement/apis/createorupdate#apimanagementcreateapinewversionusingexistingapi)

What do you think about replacing `.` with `-` in the identifier? So instead `my-api1.0` we would create `my-api1-0`.

**Comment by FelixBoers** [comment]
I've created a draft pull request. Please let me know, what you think.

**Comment by stephaneey** [comment]
Ok thanks, I'll have a look at it but I'll have to make some regression tests so it might take a bit of time. Thanks for your contribution

**Comment by FelixBoers** [comment]
Thanks for your reply. I'll try to find time to make some tests, too.

**Comment by stephaneey** [comment]
Hi Felix,

I've just reviewed your pull request and there is one non-functioning line of code. Could you please go through my comments, apply changes so that I can accept the pull request?

Thanks

**Comment by stephaneey** [comment]
Hello Felix,

I fixed the issue and republished the extension today. It should be rolled out to your tenant in the coming hours.

Thanks
Best Regards
