### ISSUE TITLE
Using "Product created by previous task" does not work if display name and name are different

### ISSUE THREAD

**Issue by thomasvdb** [stephaneey/azure-apim-extension#53]
1. Add a release step "API Management - Create or update product"
1. In the textbox "Product" configure the value "ProductNameValue"
1. In the textbox "Display name" configure the value "ProductDisplayNameValue"
1. Add a release step "API Management - Create or Update API"
1. Configure this step with the checkbox "Product created by previous task" enabled

If you run this setup, the "API Management - Create or Update API" release step will fail because it tries to find the product based on the display name instead of the value in the "Product" textbox:
../providers/Microsoft.ApiManagement/service/[api management name]/products/**ProductDisplayNameValue**/apis/...

**Comment by stephaneey** [comment]
Hi Thomas,

Thanks for reporting the issue. I'll have a look at it. Stay tunned!

Best Regards
