### ISSUE TITLE
Would like to set subscription required to false on an API

### ISSUE THREAD

**Issue by simonness** [stephaneey/azure-apim-extension#56]
I.e.

![image](https://user-images.githubusercontent.com/10990813/62123148-920be580-b2c7-11e9-9448-def705fdd98f.png)

This is available in the latest version of the REST API (2019-01-01) ([ref](https://docs.microsoft.com/en-us/rest/api/apimanagement/2019-01-01/apis/createorupdate)) as it got added in 2018-06-01-preview of the spec (https://github.com/Azure/azure-rest-api-specs/pull/4078).

**Comment by stephaneey** [comment]
Hello,

Thanks for reporting the issue, I'll have a look at it over the weekend. Stay tuned!

Best Regards

**Comment by simonness** [comment]
Hi @stephaneey thanks very much for taking a look!

**Comment by stephaneey** [comment]
Fixed in APIM v4 versioned API task
