### ISSUE TITLE
Function API: Access to the path is denied

### ISSUE THREAD

**Issue by peter-tridius** [stephaneey/azure-apim-extension#57]
Thank you for such a great DevOps task!  I am using the Functions task to register our function with APIM.

I am getting an error right off the bat though.  I am getting an "Access To the Path is Denied" exception, pointing to apimfunction.ps1: line 111

It occurs in the log right after "Enabling Swagger for the target function set" and seems to be associated with the scm url.  

![image](https://user-images.githubusercontent.com/50894999/62507353-aec58300-b7c9-11e9-9e59-d141aad3a5c4.png)

My service principal in DevOps has a Contributor role to the subscription.

**Comment by stephaneey** [comment]
Hello,

Be sure that you do not have IP restrictions defined on the SCM endpoint. If that's the case, you must use a self-hosted agent that is included in the authorized IP range.

Best Regards
