### ISSUE TITLE
ERROR Create or update versioned API: You cannot call a method on a null-valued expression

### ISSUE THREAD

**Issue by CGascon86** [stephaneey/azure-apim-extension#58]
I'm trying to publish an API into API Management using the Task  called 'API Management - Create or update versioned API' and it always return this error:
       "You cannot call a method on a null-valued expression"

What's the problem? I've fill all the fields of the task :(

Thank's :)
Regards

**Comment by thdotnet** [comment]
I am facing the same problem, do you know how to solve it?

**Comment by CGascon86** [comment]
No... I'm still having the problem :(

**Comment by stephaneey** [comment]
Hello,

Since you don't give any context (Azure DevOps Server or Services, etc.) and since I cannot reproduce this, I'll simply close the issue. Feel free to open a new one **with more details** about the problem you are facing.

Thanks
Best Regards
