### ISSUE TITLE
Create or Update Versioned API - ValidationError  Unexpected character encountered while parsing value: <

### ISSUE THREAD

**Issue by erwinkramer** [stephaneey/azure-apim-extension#61]
When using definition URL https://petstore.swagger.io/v2/swagger.json on the "API Management - Create or Update API" task, it works fine. But when using the same definition on "API Management - Create or Update Versioned API" it fails. 

I'm using ADO on-premise. The API's do get deployed and versioned, but the endpoint URL and operations are not visible. So it's not workable. 

```
2019-09-02T07:37:42.5677959Z applied authorization
2019-09-02T07:37:42.5677959Z Importing swagger 
https://management.azure.com/subscriptions/SOMEGUID/resourceGroups/SOMERESOURCEGROUP/providers/Microsoft.ApiManagement/service/SOMESERVICE/apis/petstore-demo1?import=true&api-version=2018-06-01-preview spec is v2 format is json
2019-09-02T07:37:43.6928216Z @{code=ValidationError; target=representation; message=Parsing error(s): Unexpected character encountered while parsing value: <. Path '', line 0, position 0.}
2019-09-02T07:37:43.9271725Z ##[error]The remote server returned an error: (400) Bad Request.
2019-09-02T07:37:43.9740528Z ##[section]Finishing: API Management - Create/Update API 
```

**Comment by erwinkramer** [comment]
I just found out what the core issue was;

API Management - Create or Update API: Passes the definition URL 
API Management - Create or Update Versioned API:  Downloads the definition URL and passes the content of that definition. 

Now it happens to run on a machine with limited internet connectivity, so it would return a proxy blockpage. That blockpage is XML and starts with '<'.

Maybe some more documentation about this, or info in the settings tab of the task itself would save someone else some time.

**Comment by stephaneey** [comment]
Hi,

Thanks for reporting this! Indeed, the extension has only be tested with Azure DevOps Services which has a default permanent & reliable connectivity to Internet. However, there is not much I can do about it. The "works with" section in the marketplace automatically tags extensions for both Azure DevOps Server & Services.

Best Regards
