### ISSUE TITLE
Creating or Updating an API : set the description of the API

### ISSUE THREAD

**Issue by RomainLasso** [stephaneey/azure-apim-extension#64]
Hi Stephane,

First of all thanks for this extension !

Currently, it isn't possible to define the description of the API.
Do you plan to add this feature in a future release ?

Thanks

Romain

**Comment by simonness** [comment]
+1 on this one.

**Comment by stephaneey** [comment]
Hi @RomainLasso ,

Sorry for the late answer. Yes I'll add it.

Best Regards

**Comment by stephaneey** [comment]
Just realized that API description should be defined in the Description field of the OpenAPI definition. Azure APIM takes it from there.
