### ISSUE TITLE
Creat or Upodate a Global Policy does not set the baseurl, errors out always

### ISSUE THREAD

**Issue by sethwenzel** [stephaneey/azure-apim-extension#65]
errors out with:

`##[error]Invalid URI: The hostname could not be parsed.`

apimglobalpolicy.ps1 line 88 references baseurl, but never sets the variable

**Comment by stephaneey** [comment]
Hello,

Fixed, I merge @simonness's pull request!

Thanks

**Comment by simonness** [comment]
Thanks @stephaneey! 👍
