### ISSUE TITLE
Create or update API does not set Web Service URL

### ISSUE THREAD

**Issue by jwakeen** [stephaneey/azure-apim-extension#66]
It does not appear there is a form field to set the web service url from the the Azure DevOps task. The web service url is actually cleared when running this task on an existing API. I have not tried the creation path.

**Comment by elvirdolic** [comment]
I have the same experience but with OpenApi 3.0

**Comment by stephaneey** [comment]
Thanks @elvirdolic  for having answered!

**Comment by MattHartz** [comment]
Didn't fix it for me :(
