### ISSUE TITLE
Azure function v2 compatibility

### ISSUE THREAD

**Issue by TenChiHan** [stephaneey/azure-apim-extension#68]
Hello,

Do you plan to implement compatibility with azure functions v2 ?

**Comment by stephaneey** [comment]
Hello,

Microsoft changed completely the way to integrate with Azure Functions which do not produce API definitions anymore. That was already a hard work to get it done for v1, now I'm afraid that I won't be able to adapt. I'll have a look but do not count too much on it.

Thanks
Best Regards

**Comment by stephaneey** [comment]
Hello,

I have checked and that's kind of a nightmare so I guess, I won't implement it, sorry!

Best Regards
