### ISSUE TITLE
Unnecessarily required groups in Product creation

### ISSUE THREAD

**Issue by michaldudak** [stephaneey/azure-apim-extension#70]
The `groups` parameter should not be required in the `apimcreateorupdateproduct` task.
Groups are not available in the Consumption tier and the task fails when ran against such a tier.

**Comment by stephaneey** [comment]
Hi Michal,

Note that the extension has never been tested with the consumption tier which has its own way of working. For the time being, I don't plan to take it into account but feel free to contribute :)

Best Regards
