### ISSUE TITLE
 Internal Server Error while publishing Azure Function App into API Management Service Instance

### ISSUE THREAD

**Issue by mayuribhavsar23** [stephaneey/azure-apim-extension#75]
Hi,

I am trying to import Function APP APIs into API MS Instance using API Management - Create or Update against Azure Function. I am continuously getting Internal Server Error, not able to know the exact issue. I tried by adding VSTS service principal in both API MS and Azure Function Access Control with Contributor role. Also enabled Managed Identity on Azure function. Thanks

**Comment by stephaneey** [comment]
Hello,

Beware that it only works with V1 functions (as indicated in the task itself). Microsoft changed radically the way they handle OpenAPI with Azure Functions for V2 and V3 and I'm unlikely going to migrate this given the amount of work and no warranty of a bit of stability on the MS side. However, I'll have a look at it still :)

Thanks
Best Regards

**Comment by mayuribhavsar23** [comment]
Sure. Thanks for your quick response. Is there any other way to integrate
Function App APIs with API Management Service VSTS extension instead of
Azure function - like directly adding API url? as I am not sure how can I
generate swagger json for azure function?

Thanks & Regards,
Mayuri

**Comment by stephaneey** [comment]
That's precisely what does not work anymore, generating the OpenAPI definition. I don't know why MS changed this.
