### ISSUE TITLE
More control over Revisions

### ISSUE THREAD

**Issue by Peppers911** [stephaneey/azure-apim-extension#76]
Right now I'm glad to see support for Revisions, but right now we do not have any way of making created revision current or disabling existing one.

Is there any change of getting a new Task for setting specific Revision to Current?

**Comment by stephaneey** [comment]
I could indeed add a "create and promote" new revision although I'm a bit scared that people would start to make errors, that's why I left the publishing of a new revision aside so that people really need to do it purposely.

**Comment by stephaneey** [comment]
Hi,

I have implemented it and I have just released it on the marketplace.

Best Regards

**Comment by Peppers911** [comment]
Thank you
