### ISSUE TITLE
Option to specify different API URL suffix from Name

### ISSUE THREAD

**Issue by DirkJelleseInh** [stephaneey/azure-apim-extension#8]
When API is created Name is used in API-URL suffix, would like to gave an option to differ from name.

**Comment by tomkerkhove** [comment]
I'm not sure if I'm understanding your request, can you please elaborate more and/or add a screenshot?

If you want to have an api suffix on the gateway that is different from the name you can simply change that during or after creation of the api itself.

**Comment by DirkJelleseInh** [comment]
[cid:image001.png@01D419F8.3FFE20F0]
We are deploying from a swagger file, but in the end we will get https://apitstinh.azure-api.net/tst-onderwijsinstelling/v2-api/onderwijsinstelling/onderwijseenheden.

If we can modify the base url. To test and keer the name tst-onderwijsinstellingv2-api that would be awesome. If we modify the URL in azure it still works, however next deployment the API URL suffix will be overwritten again with full name.

So only if API URL Suffix –eq “” it should copy Name, else it should use the suffix given in deployment.

Kindest Regards,

Dirk Jellese
Informatie Voorziening & Technologie (IVT) – Technisch Applicatie Beheer

**Comment by tomkerkhove** [comment]
Unfortunately I cannot see the image that you've added but when you import - Do you do it in the portal or via PowerShell?

**Comment by stephaneey** [comment]
Hi,

 @tomkerkhove  I guess they just use my extension to deploy their API and indeed, I'm not offering any option for the API suffix as you have in the portal. I will rework the extension, you can expect to have a V2 anytime soon. I'm just back from Japan so I had no time but I will try to work on it soon.

Thanks
Best Regards

**Comment by DirkJelleseInh** [comment]
Hello,

That would be awesome, it is our last piece of the puzzle for deployment via TFS/VSTS.
I’ll try to make a public folder on my OneDrive to share the screenshots for the future.

I’m trying to get familiar with GitHub, the desktop program is not doing what it should on my laptop.
I don’t know if you appreciate any extra’s via a fork, let me know. Maybe I can contribute to your great work.
I use powershell a lot to make any task easier.

Kindest regards,
Dirk Jellese

**Comment by DirkJelleseInh** [comment]
![api_screen_shot](https://user-images.githubusercontent.com/41152313/42746464-29e1c6f6-88d8-11e8-8e4e-72728ebee2db.jpg)

**Comment by DirkJelleseInh** [comment]
I added the screenshot I was talking about.

**Comment by lurumad** [comment]
Hi @DirkJelleseInh 

Something like this

![suffix](https://user-images.githubusercontent.com/1729519/43201485-f2071f90-9018-11e8-8c4b-81b9b38b415c.png)

I need time to make a PR.

Regards!

**Comment by DirkJelleseInh** [comment]
@lurumad yes that's the part we would like to controle separate of the name

**Comment by stephaneey** [comment]
@DirkJelleseInh  @lurumad  I'm working on this, I'm fixing the easiest problems first :) but I'll definitely work on that one too.

**Comment by lurumad** [comment]
Hi @stephaneey 

I've done this in a private branch.

Regards!

**Comment by stephaneey** [comment]
Hi @lurumad 

Might be interesting to share so that I don't reinvent the wheel. 

Thanks

**Comment by lurumad** [comment]
Done in #9

Regards!

**Comment by stephaneey** [comment]
Hello,

Great, thanks! Just published a new release on the market place.

**Comment by gsscoder** [comment]
I set it using [New-AzApiManagementApi](https://docs.microsoft.com/en-us/powershell/module/az.apimanagement/new-azapimanagementapi?view=azps-3.8.0) specifying `-`Path`.

The problem is that you can't left it blank, like for `-ServiceUrl`.

A _workaround_ maybe using directly `New-AzResource` directly, but I had problems defining versions in such case.

See this S.O. question: https://stackoverflow.com/questions/60882705/azure-create-a-new-api-management-service-without-a-service-url/60962169?noredirect=1#comment107926794_60962169.
