### ISSUE TITLE
Specify scheme to https for API

### ISSUE THREAD

**Issue by plec** [stephaneey/azure-apim-extension#90]
Hi,

We're using the azure-apim-extension to update our swagger API definition, thanks for this extension that skip manual operations !

We have one problem about specify the URL scheme to HTTPS of our API. We don't find any parameter in the task to specify that value.

We'v tried to use both v3 and v4 of the task without any success. Is it possible to do so with azure-apim-extension ?
![APIM-scheme](https://user-images.githubusercontent.com/4046655/84522652-55768c00-acd7-11ea-959e-ff2bacacd93f.png)

**Comment by stephaneey** [comment]
Hello,

It is normal since it comes from the openapi definition itself. In OpenAPI 2.0, there is an explicit schemes array while in 3.0, it is directly specified in the serverUrl attribute

Best Regards
