### ISSUE TITLE
500 error during the step - 'Enabling Swagger for the target function set'.

### ISSUE THREAD

**Issue by lamelyan** [stephaneey/azure-apim-extension#97]
When I try to run a release task 'API Management - Create or Update API on Azure Functions (v1)' I get a 500 error during the step - 'Enabling Swagger for the target function set'.

![2020-08-10_15-17-44](https://user-images.githubusercontent.com/1872686/89836408-53d91100-db2c-11ea-92c0-69e8aa5cd1e3.jpg)

I believe this has to do with how my function app is published. It's in read-only mode, so you can't update its files and I think the task is trying to update the host.json.
![2020-08-10_15-18-03](https://user-images.githubusercontent.com/1872686/89836436-62272d00-db2c-11ea-950e-2cdc335de551.jpg)

Is this correct? If so, will this not work with function apps that are published in read-only mode?

**Comment by stephaneey** [comment]
Hello,

As stated in the task title, the extension only works with Azure Functions v1 not above because Microsoft completely changed the way functions's OpenAPI definitions are being generated.

Best Regards
